### ISSUE TITLE
Add Composer Support

### ISSUE THREAD

**Issue by actionspec** [actionspec/php74-apache#1]
Need headless composer support. Should be able to feed composer file straight to the container at runtime.

**Comment by rickconlee** [comment]
So, I added this to the Dockerfile on my local branch: 

`# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer`

The problem that I see here, is the use case. Lets say, for example, A user is using this on a production image, and there is some kind of orchestration in play (K8's, Swarm, etc.) - every time a container spins up, it will need to run composer, and if there is a long list of dependencies, that would be a huge issue. Ideally, those deps would be built in when the particular runtime image is built. 

What's the use case for this? Is this strictly for development, or are you using this for prod and staging too?

**Comment by actionspec** [comment]
The use pattern we had in mind is that of a general purpose image that we can use everywhere. We would be using this as a base image for other builds.

**Comment by actionspec** [comment]
Assigned @rickconlee to the issue.
